/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apucsc_1.pkg2;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author ZAHIRUL
 */
public class GUI_39 extends javax.swing.JFrame {

    /**
     * Creates new form GUI_39
     */
    public GUI_39() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REMOVE LIGHT");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 388));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("REMOVE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("JOB");

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\yr 2 semester 1\\OODJ\\Assignment\\APU car service centre 1.2\\final\\APU Automotive car service centre\\icons\\converted\\manager ui.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(85, 85, 85))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ENTER TICKET:");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("REMOVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(jButton2)))
                        .addGap(0, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //BACK************************************************************
        setVisible(false);
        new GUI_37().setVisible(true);
        //BACK************************************************************
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //REMOVE***********************************************************
        String inTicket = jTextField1.getText().trim();
        String cus = "";
        boolean flag = false,flag_2 = false,flag_3 = false;
        for(int i=0;i<APUCSC_12.allLightDuty.size();i++)
        {
            if(APUCSC_12.allLightDuty.get(i).getTicketNumber().equals(inTicket))
            {
                cus = APUCSC_12.allLightDuty.get(i).getCusID().getId();
                flag = true;
                break;
            }
        }
        if(flag)
        {
            String a = JOptionPane.showInputDialog("TICKET FOUND! DO YOU WANT TO DELETE: 'yes' OR 'no");
            a = a.trim();
            if(a.equalsIgnoreCase("yes"))
            {
                flag_2 = true;
                String originalFilePath = "light_duty.txt";
                String tempFilePath = "temp.txt";
                File oldFile = new File(originalFilePath);
                File newFile = new File(tempFilePath);
                String techs = "";
                String day = "";
                int start_time = 0;
                int finish_time = 0;
                String ticket_number = "";
                String cus_name = "";
                String cus_id = "";
                try
                {
                    FileWriter fw = new FileWriter(tempFilePath,true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    Scanner s = new Scanner(new File(originalFilePath));
                    while(s.hasNext())
                    {
                        techs = s.nextLine();
                        day = s.nextLine();
                        start_time = Integer.parseInt(s.nextLine());
                        finish_time = Integer.parseInt(s.nextLine());
                        ticket_number = s.nextLine();
                        cus_name = s.nextLine();
                        cus_id = s.nextLine();
                        s.nextLine();
                        if(!ticket_number.equals(inTicket))
                        {
                            pw.println(techs);
                            pw.println(day);
                            pw.println(start_time);
                            pw.println(finish_time);
                            pw.println(ticket_number);
                            pw.println(cus_name);
                            pw.println(cus_id);
                            pw.println();
                        }
                    }
                    s.close();
                    pw.flush();
                    pw.close();
                    oldFile.delete();
                    File dump = new File(originalFilePath);
                    newFile.renameTo(dump);
                }
                catch(Exception e)
                {
                    
                }
            }
            else if(a.equalsIgnoreCase("no"))
            {
                setVisible(false);
                new GUI_39().setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "Please pay attention to the instructions");
        }
        if(flag_2)
        {
            flag_3 = false;
            String originalFilePath = "ticket.txt";
            String tempFilePath = "temp2.txt";
            File oldFile = new File(originalFilePath);
            File newFile = new File(tempFilePath);
            String ticket_number = "";
            String pay = "";
            String cus_name = "";
            String cus_id = "";
            String techID = "";
            try
            {
                FileWriter fw = new FileWriter(tempFilePath,true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter pw = new PrintWriter(bw);
                Scanner s = new Scanner(new File(originalFilePath));
                while(s.hasNext())
                {
                    ticket_number = s.nextLine();
                    pay = s.nextLine();
                    cus_name = s.nextLine();
                    cus_id = s.nextLine();
                    techID = s.nextLine();
                    s.nextLine();
                    if(!ticket_number.equals(inTicket))
                    {
                        pw.println(ticket_number);
                        pw.println(pay);
                        pw.println(cus_name);
                        pw.println(cus_id);
                        pw.println(techID);
                        pw.println();
                    }
                }
                s.close();
                pw.flush();
                pw.close();
                oldFile.delete();
                File dump = new File(originalFilePath);
                newFile.renameTo(dump);
            }
            catch(Exception e)
            {
                
            }
        }
        if(flag_3)
        {
            String originalFilePath3 = "customer.txt";
            String tempFilePath3 = "temp3.txt";
            File oldFile3 = new File(originalFilePath3);
            File newFile3 = new File(tempFilePath3);
            String cusID3 = "";
            String cusName3 = "";
            String email = "";
            String phoneNumber = "";
            try
            {
                FileWriter fw = new FileWriter(tempFilePath3,true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter pw = new PrintWriter(bw);
                Scanner s = new Scanner(new File(originalFilePath3));
                while(s.hasNext())
                {
                    cusID3 = s.nextLine();
                    cusName3 = s.nextLine();
                    email = s.nextLine();
                    phoneNumber = s.nextLine();
                    s.nextLine();
                    if(!cus.equals(cusID3))
                    {
                        pw.println(cusID3);
                        pw.println(cusName3);
                        pw.println(email);
                        pw.println(phoneNumber);
                        pw.println();
                    }
                }
                s.close();
                pw.flush();
                pw.close();
                oldFile3.delete();
                File dump3 = new File(originalFilePath3);
                newFile3.renameTo(dump3);
            }
            catch(Exception e)
            {

            }
            try
            {
                APUCSC_12.allTicket = null;
                Scanner s = new Scanner(new File("ticket.txt"));
                while(s.hasNext())
                {
                    String a = s.nextLine();
                    String b = s.nextLine();
                    String c = s.nextLine();
                    String d = s.nextLine();
                    String e = s.nextLine();
                    s.nextLine();
                    Customer customer = null;
                    for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                    {
                        Customer x = APUCSC_12.allCustomer.get(i);
                        if(c.equals(x.getName()))
                        {
                            customer = x;
                            break;
                        }
                    }
                    Customer id = null;
                    for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                    {
                        Customer x = APUCSC_12.allCustomer.get(i);
                        if(d.equals(x.getId()))
                        {
                            id = x;
                            break;
                        }
                    }
                    Techs worker = null;
                    for(int i=0;i<APUCSC_12.allTechs.size();i++)
                    {
                        Techs x = APUCSC_12.allTechs.get(i);
                        if(e.equals(x.getUserId()));
                        {
                            worker = x;
                            break;
                        }
                    }
                    Ticket t = new Ticket(a,b,customer,id,worker);
                    APUCSC_12.allTicket.add(t);
                }
                s.close();
            }
            catch(Exception e)
            {

            }
            try
            {
                APUCSC_12.allCustomer = null;
                Scanner s = new Scanner(new File("customer.txt"));
                while(s.hasNext())
                {
                    String a = s.nextLine();
                    String b = s.nextLine();
                    String c = s.nextLine();
                    String d = s.nextLine();
                    s.nextLine();
                    Customer cust = new Customer(a,b,c,d);
                    APUCSC_12.allCustomer.add(cust);
                }
                s.close();
            }
            catch(Exception e)
            {

            }
            try
            {
                APUCSC_12.allLightDuty = null;
                Scanner s = new Scanner(new File("light_duty.txt"));
                while(s.hasNext())
                {
                    String a = s.nextLine();
                    String b = s.nextLine();
                    int c = Integer.parseInt(s.nextLine());
                    int d = Integer.parseInt(s.nextLine());
                    String e = s.nextLine();
                    String f = s.nextLine();
                    String g = s.nextLine();
                    s.nextLine();
                    Techs worker = null;
                    for(int i=0;i<APUCSC_12.allTechs.size();i++)
                    {
                        Techs x = APUCSC_12.allTechs.get(i);
                        if(a.equals(x.getUserId()))
                        {
                            worker = x;
                            break;
                        }
                    }
                    Customer cust = null;
                    for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                    {
                        Customer x = APUCSC_12.allCustomer.get(i);
                        if(f.equals(x.getName()))
                        {
                            cust = x;
                            break;
                        }
                    }
                    Customer id = null;
                    for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                    {
                        Customer x = APUCSC_12.allCustomer.get(i);
                        if(g.equals(x.getId()))
                        {
                            id = x;
                            break;
                        }
                    }
                    Ticket t = null;
                    for(int i=0;i<APUCSC_12.allTicket.size();i++)
                    {
                        Ticket x = APUCSC_12.allTicket.get(i);
                        if(e.equals(x.getTicketNumber()))
                        {
                            t = x;
                            break;
                        }
                    }
                    LightDuty ld = new LightDuty(worker,b,c,d,t,cust,id);
                    APUCSC_12.allLightDuty.add(ld);
                }
                s.close();
            }
            catch(Exception e)
            {

            }
        }
        else
            JOptionPane.showMessageDialog(this, "TICKET NOT FOUND!");
        //REMOVE***********************************************************
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_39.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_39.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_39.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_39.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_39().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
