/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apucsc_1.pkg2;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Random;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ZAHIRUL
 */
public class GUI_44 extends javax.swing.JFrame {

    /**
     * Creates new form GUI_44
     */
    
    DefaultListModel dm = new DefaultListModel();
    
    public GUI_44() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HEAVY DUTY JOB");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 388));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("HEAVY DUTY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("JOB");

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\yr 2 semester 1\\OODJ\\Assignment\\APU car service centre 1.2\\final\\APU Automotive car service centre\\icons\\converted\\techs ui.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(100, 100, 100))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ENTER TICKET NUMBER:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("SHOW JOBS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jButton3))
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //BACK*************************************************************
        setVisible(false);
        new GUI_3().setVisible(true);
        //BACK*************************************************************
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //DONE*************************************************************
        String ticketNumber = jTextField1.getText().trim();
        boolean flag = false;
        String cus="";
        for(int i=0;i<APUCSC_12.allHeavyDuty.size();i++)
        {
            if(APUCSC_12.allHeavyDuty.get(i).getTicketNumber().getTicketNumber().equals(ticketNumber))
            {
                cus = APUCSC_12.allHeavyDuty.get(i).getCusID().getId();
                flag = true;
                break;
            }
        }
        if(flag)
        {
            String a = JOptionPane.showInputDialog("TICKET FOUND! Final confirmation 'DONE' OR 'NOT DONE'");
            a = a.trim();
            if(a.equalsIgnoreCase("DONE"))
            {
                String originalFilePath = "heavy_duty.txt";
                String tempFilePath = "temp.txt";
                File oldFile = new File(originalFilePath);
                File newFile = new File(tempFilePath);
                String tech_id = "";
                String day = "";
                int start_time = 0;
                int finish_time = 0;
                String ticket = "";
                String cus_name = "";
                String cus_id = "";
                try
                {
                    FileWriter fw = new FileWriter(tempFilePath,true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    Scanner s = new Scanner(new File(originalFilePath));
                    while(s.hasNext())
                    {
                        tech_id = s.nextLine();
                        day = s.nextLine();
                        start_time = Integer.parseInt(s.nextLine());
                        finish_time = Integer.parseInt(s.nextLine());
                        ticket = s.nextLine();
                        cus_name = s.nextLine();
                        cus_id = s.nextLine();
                        s.nextLine();
                        if(!ticket.equals(ticketNumber))
                        {
                            pw.println(tech_id);
                            pw.println(day);
                            pw.println(start_time);
                            pw.println(finish_time);
                            pw.println(ticket);
                            pw.println(cus_name);
                            pw.println(cus_id);
                            pw.println();
                        }
                    }
                    s.close();
                    pw.flush();
                    pw.close();
                    oldFile.delete();
                    File dump = new File(originalFilePath);
                    newFile.renameTo(dump);
                    try
                    {
                        Random rnd = new Random();
                        int ran = rnd.nextInt(2000)+1;
                        String pdfReceipt = ticketNumber+ran+".pdf";
                        Document document = new Document();
                        PdfWriter.getInstance(document, new FileOutputStream(pdfReceipt));
                        document.open();
                        String aa;
                        String bb;
                        String cc;
                        String dd;
                        String ee;
                        Scanner ss = new Scanner(new File("ticket.txt"));
                        while(ss.hasNext())
                        {
                            aa = ss.nextLine();
                            bb = ss.nextLine();
                            cc = ss.nextLine();
                            dd = ss.nextLine();
                            ee = ss.nextLine();
                            ss.nextLine();
                            if(aa.equals(ticketNumber))
                            {
                                Paragraph para = new Paragraph("TICKET NO.: "+aa+"\n"+"CHARGE: RM"+bb+"\n"+"NAME: "+cc+"\n"+"ID: "+dd+"\n"+"TECHNICIAN'S ID: "+ee);
                                document.add(para);
                                break;
                            }
                        }
                        ss.close();
                        document.close();
                    }
                    catch(Exception e)
                    {
                        
                    }
                }
                catch(Exception e)
                {
                    
                }
                String originalFilePath2 = "ticket.txt";
                String tempFilePath2 = "temp2.txt";
                File oldFile2 = new File(originalFilePath2);
                File newFile2 = new File(tempFilePath2);
                String ticket_number = "";
                String pay = "";
                String cus_name2 = "";
                String cus_id2 = "";
                String techID2 = "";
                try
                {
                    FileWriter fw = new FileWriter(tempFilePath2,true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    Scanner s = new Scanner(new File(originalFilePath2));
                    while(s.hasNext())
                    {
                        ticket_number = s.nextLine();
                        pay = s.nextLine();
                        cus_name2 = s.nextLine();
                        cus_id2 = s.nextLine();
                        techID2 = s.nextLine();
                        s.nextLine();
                        if(!ticket_number.equals(ticketNumber))
                        {
                            pw.println(ticket_number);
                            pw.println(pay);
                            pw.println(cus_name2);
                            pw.println(cus_id2);
                            pw.println(techID2);
                            pw.println();
                        }
                    }
                    s.close();
                    pw.flush();
                    pw.close();
                    oldFile2.delete();
                    File dump2 = new File(originalFilePath2);
                    newFile2.renameTo(dump2);
                }
                catch(Exception e)
                {
                    
                }
                String originalFilePath3 = "customer.txt";
                String tempFilePath3 = "temp3.txt";
                File oldFile3 = new File(originalFilePath3);
                File newFile3 = new File(tempFilePath3);
                String cusID3 = "";
                String cusName3 = "";
                String email = "";
                String phoneNumber = "";
                try
                {
                    FileWriter fw = new FileWriter(tempFilePath3,true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    Scanner s = new Scanner(new File(originalFilePath3));
                    while(s.hasNext())
                    {
                        cusID3 = s.nextLine();
                        cusName3 = s.nextLine();
                        email = s.nextLine();
                        phoneNumber = s.nextLine();
                        s.nextLine();
                        if(!cus.equals(cusID3))
                        {
                            pw.println(cusID3);
                            pw.println(cusName3);
                            pw.println(email);
                            pw.println(phoneNumber);
                            pw.println();
                        }
                    }
                    s.close();
                    pw.flush();
                    pw.close();
                    oldFile3.delete();
                    File dump3 = new File(originalFilePath3);
                    newFile3.renameTo(dump3);
                }
                catch(Exception e)
                {
                    
                }
                setVisible(false);
                new GUI_3().setVisible(true);
            }
            else if(a.equalsIgnoreCase("NOT DONE"))
            {
                setVisible(false);
                new GUI_43().setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "Please pay attention to the instructions");
        }
        else
            JOptionPane.showMessageDialog(this, "TICKET NOT FOUND!");
        //DONE*************************************************************
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //SHOW JOBS********************************************************
        String techID = APUCSC_12.loginT.getUserId();
        jList1.setModel(dm);
        dm.removeAllElements();
        try
        {
           Scanner s = new Scanner(new File("heavy_duty.txt"));
           while(s.hasNext())
           {
               String a = s.nextLine();
               String b = s.nextLine();
               int c = Integer.parseInt(s.nextLine());
               int d = Integer.parseInt(s.nextLine());
               String e = s.nextLine();
               String f = s.nextLine();
               String g = s.nextLine();
               s.nextLine();
               if(a.equals(techID))
               {
                   dm.addElement("TICKET N0.: "+e);//ticket number
                   dm.addElement("CUSTOMER ID: "+g);//cus id
                   dm.addElement("CUSTOMER NAME: "+f);//cus name
                   dm.addElement("DAY: "+b);//day
                   dm.addElement("TIME "+c+"PM");//start time
                   dm.addElement("\n");
               }
           }
           s.close();
        }
        catch(Exception e)
        {
            
        }
        //SHOW JOBS********************************************************
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_44().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
