/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apucsc_1.pkg2;

import java.io.File;
import java.io.PrintWriter;
import java.util.Random;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ZAHIRUL
 */
public class GUI_48 extends javax.swing.JFrame {

    /**
     * Creates new form GUI_48
     */
    private String name;
    private String email;
    private String phoneNumber;
    private String day;
    private int startTime;
    private int finishTime;
    private boolean check;
    
    DefaultListModel dm = new DefaultListModel();
    DefaultListModel dm2 = new DefaultListModel();
    public GUI_48() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ASSIGN JOB");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 388));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TECHNICIANS");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("ENTER CUSTOMER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\yr 2 semester 1\\OODJ\\Assignment\\APU car service centre 1.2\\final\\APU Automotive car service centre\\icons\\converted\\admin.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4)
                        .addComponent(jLabel2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jButton1))))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(72, 72, 72))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("WORKIGN ON THE DAY AND TIME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ALL TECHNICIANS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TECHNICIAN ID:");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jList2);

        jScrollPane1.setViewportView(jList3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(116, 116, 116))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 313, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //CLOSE***********************************************************
        setVisible(false);
        new GUI_4().setVisible(true);
        
        //CLOSE***********************************************************
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //TECHS ID*********************************************************
        if(check)
        {
            String inTechId = jTextField1.getText().trim();
            boolean flag = false,flag_2 = false;
            String ticketNumber="";
            String ID = "";
            Random rnd = new Random();
            for(int i=0;i<APUCSC_12.allLightDuty.size();i++)
            {
                if(APUCSC_12.allLightDuty.get(i).getDay().equals(day) & APUCSC_12.allLightDuty.get(i).getBeginTime()==startTime & APUCSC_12.allLightDuty.get(i).getEndTime()==finishTime)
                {
                    String a = APUCSC_12.allLightDuty.get(i).getWorker().getUserId();
                    if(a.equals(inTechId))
                    {
                        JOptionPane.showMessageDialog(this, "TECHNICIANS BOOKED OR WORKING AT THAT TIME AND DAY!!");
                        flag = true;
                        break;
                    }
                }
            }
            if(flag==false)
            {
                boolean cusList = APUCSC_12.allCustomer.isEmpty();
                if(cusList==true)
                {
                    int ran = rnd.nextInt(1000)+1;
                    String sran = String.valueOf(ran); 
                    ID = sran;
                }
                else
                {
                    for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                    {
                        int ran = rnd.nextInt(1000)+1;
                        String sran = String.valueOf(ran);
                        if(!APUCSC_12.allCustomer.get(i).getId().equals(sran))
                        {
                            ID = sran;
                            break;
                        }
                    }
                }
                String a = JOptionPane.showInputDialog("You charge is RM100");
                int b = Integer.parseInt(a);
                if(b>100)
                {
                    JOptionPane.showMessageDialog(this, "You change is RM"+ (b-100));
                    boolean ticketList = APUCSC_12.allTicket.isEmpty();
                    if(ticketList==true)
                    {
                        int ran = rnd.nextInt(1000)+1;
                        flag_2 = true;
                        ticketNumber = "CS"+ran;
                    }
                    else
                    {
                        for(int i=0;i<APUCSC_12.allTicket.size();i++)
                        {
                            int ran = rnd.nextInt(1000)+1;
                            String c = APUCSC_12.allTicket.get(i).getTicketNumber();
                            int len = c.length();
                            String d = c.substring(2,len);
                            int oldTicket = Integer.parseInt(d);
                            if(ran!=oldTicket)
                            {
                                flag_2 = true;
                                ticketNumber = "CS"+ran;
                                break;
                            }
                        }
                    }
                }
                else
                {
                    if(b<100)
                    {
                        JOptionPane.showMessageDialog(this, "You have paid RM"+ (100-b) +" less" );
                    }
                    int newCharge;
                    newCharge = 100-b;
                    while(newCharge>0)
                    {
                        String c = JOptionPane.showInputDialog("You charge is RM"+newCharge);
                        int d = Integer.parseInt(c);
                        newCharge = newCharge-d;
                    }
                    if(newCharge==0)
                    {
                        boolean ticketList = APUCSC_12.allTicket.isEmpty();
                        if(ticketList==true)
                        {
                            int ran = rnd.nextInt(1000)+1;
                            flag_2 = true;
                            ticketNumber = "CS"+ran;
                        }
                        else
                        {
                            for(int i=0;i<APUCSC_12.allTicket.size();i++)
                            {
                                int ran = rnd.nextInt(1000)+1;
                                String c = APUCSC_12.allTicket.get(i).getTicketNumber();
                                int len = c.length();
                                String d = c.substring(2,len);
                                int oldTicket = Integer.parseInt(d);
                                if(ran!=oldTicket)
                                {
                                    flag_2 = true;
                                    ticketNumber = "CS"+ran;
                                    break;
                                }
                            }
                        }
                    }
                    else if(newCharge<0)
                    {
                        JOptionPane.showMessageDialog(this,"You change is RM"+(newCharge*-1));
                        boolean ticketList = APUCSC_12.allTicket.isEmpty();
                        if(ticketList==true)
                        {
                            int ran = rnd.nextInt(1000)+1;
                            flag_2 = true;
                            ticketNumber = "CS"+ran;
                        }
                        else
                        {
                            for(int i=0;i<APUCSC_12.allTicket.size();i++)
                            {
                                int ran = rnd.nextInt(1000)+1;
                                String c = APUCSC_12.allTicket.get(i).getTicketNumber();
                                int len = c.length();
                                String d = c.substring(2,len);
                                int oldTicket = Integer.parseInt(d);
                                if(ran!=oldTicket)
                                {
                                    flag_2 = true;
                                    ticketNumber = "CS"+ran;
                                    break;
                                }
                            }
                        }
                    }
                }
                if(flag_2=true)
                    {
                    JOptionPane.showMessageDialog(this, "CUSTOMER ID: "+ID+ " TICKET NO.: "+ticketNumber+" Your TECHNICIAN: "+inTechId);
                    try
                    {
                        Customer cus = new Customer(ID,name,email,phoneNumber);
                        APUCSC_12.allCustomer.add(cus);
                        PrintWriter pw = new PrintWriter("customer.txt");
                        for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                        {
                            pw.println(APUCSC_12.allCustomer.get(i).getId());
                            pw.println(APUCSC_12.allCustomer.get(i).getName());
                            pw.println(APUCSC_12.allCustomer.get(i).getEmail());
                            pw.println(APUCSC_12.allCustomer.get(i).getPhoneNo());
                            pw.println();
                        }
                        pw.flush();
                        pw.close();
                    }
                    catch(Exception e)
                    {

                    }
                    try
                    {
                        for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                        {
                            if(name.equals(APUCSC_12.allCustomer.get(i).getName()))
                            {
                                APUCSC_12.customerName = APUCSC_12.allCustomer.get(i);
                                break;
                            }
                        }
                        for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                        {
                            if(ID.equals(APUCSC_12.allCustomer.get(i).getId()))
                            {
                                APUCSC_12.customerID = APUCSC_12.allCustomer.get(i);
                                break;
                            }
                        }
                        for(int i=0;i<APUCSC_12.allTechs.size();i++)
                        {
                            if(inTechId.equals(APUCSC_12.allTechs.get(i).getUserId()))
                            {
                                APUCSC_12.techs = APUCSC_12.allTechs.get(i);
                                break;
                            }
                        }
                        Ticket ticket = new Ticket(ticketNumber,"100",APUCSC_12.customerName,APUCSC_12.customerID,APUCSC_12.techs);
                        APUCSC_12.allTicket.add(ticket);
                        PrintWriter pw = new PrintWriter("ticket.txt");
                        for(int i=0;i<APUCSC_12.allTicket.size();i++)
                        {
                            pw.println(APUCSC_12.allTicket.get(i).getTicketNumber());
                            pw.println(APUCSC_12.allTicket.get(i).getCharge());
                            pw.println(APUCSC_12.allTicket.get(i).getCustomer().getName());
                            pw.println(APUCSC_12.allTicket.get(i).getId().getId());
                            pw.println(APUCSC_12.allTicket.get(i).getWorker().getUserId());
                            pw.println();
                        }
                        pw.flush();
                        pw.close();
                    }
                    catch(Exception e)
                    {

                    }
                    try
                    {
                        for(int i=0;i<APUCSC_12.allTechs.size();i++)
                        {
                            if(inTechId.equals(APUCSC_12.allTechs.get(i).getUserId()))
                            {
                                APUCSC_12.techs = APUCSC_12.allTechs.get(i);
                                break;
                            }
                        }
                        for(int i=0;i<APUCSC_12.allTicket.size();i++)
                        {
                            if(ticketNumber.equals(APUCSC_12.allTicket.get(i).getTicketNumber()))
                            {
                                APUCSC_12.ticket = APUCSC_12.allTicket.get(i);
                                break;
                            }
                        }
                        for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                        {
                            if(name.equals(APUCSC_12.allCustomer.get(i).getName()))
                            {
                                APUCSC_12.customerName = APUCSC_12.allCustomer.get(i);
                                break;
                            }
                        }
                        for(int i=0;i<APUCSC_12.allCustomer.size();i++)
                        {
                            if(ID.equals(APUCSC_12.allCustomer.get(i).getId()))
                            {
                                APUCSC_12.customerID = APUCSC_12.allCustomer.get(i);
                                break;
                            }
                        }
                        LightDuty ld = new LightDuty(APUCSC_12.techs,day,startTime,finishTime,APUCSC_12.ticket,APUCSC_12.customerName,APUCSC_12.customerID);
                        APUCSC_12.allLightDuty.add(ld);
                        PrintWriter pw = new PrintWriter("light_duty.txt");
                        for(int i=0;i<APUCSC_12.allLightDuty.size();i++)
                        {
                            pw.println(APUCSC_12.allLightDuty.get(i).getWorker().getUserId());
                            pw.println(APUCSC_12.allLightDuty.get(i).getDay());
                            pw.println(APUCSC_12.allLightDuty.get(i).getBeginTime());
                            pw.println(APUCSC_12.allLightDuty.get(i).getEndTime());
                            pw.println(APUCSC_12.allLightDuty.get(i).getTicketNumber().getTicketNumber());
                            pw.println(APUCSC_12.allLightDuty.get(i).getCusName().getName());
                            pw.println(APUCSC_12.allLightDuty.get(i).getCusID().getId());
                            pw.println();
                        }
                        pw.flush();
                        pw.close();
                    }
                    catch(Exception e)
                    {

                    }
                    setVisible(false);
                    new GUI_4().setVisible(true);
                }
            }
              
        }
        else
            JOptionPane.showMessageDialog(this,"Enter Customer Details First!!");
        
        //TECHS ID*********************************************************
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        //CUSTOMER*********************************************************
        name = JOptionPane.showInputDialog("Enter Customer Name");
        email = JOptionPane.showInputDialog("Enter Email");
        phoneNumber = JOptionPane.showInputDialog("Enter Phone Number");
        if(!name.equals(null))
            if(!email.equals(null))
                if(!phoneNumber.equals(null))
                {
                    day = JOptionPane.showInputDialog("Enter day - [MON,TUE,WED,THUR,FRI]");
                    if(day.equalsIgnoreCase("MON")||day.equalsIgnoreCase("TUE")||day.equalsIgnoreCase("WED")||day.equalsIgnoreCase("THUR")||day.equalsIgnoreCase("FRI"))
                    {
                        String a = JOptionPane.showInputDialog("Enter Time [6AM - 11AM]");
                        startTime = Integer.parseInt(a);
                        finishTime = startTime+1;
                        if(startTime==6||startTime==7||startTime==8||startTime==9||startTime==10||startTime==11)
                        {
                            check = true;
                        }
                        else
                            JOptionPane.showMessageDialog(this, "WRONG INPUT!!");
                    }
                    else
                        JOptionPane.showMessageDialog(this, "WRONG INPUT!!");
                }
        else
                {
                    setVisible(false);
                    new GUI_4().setVisible(true);
                }
        if(check)
        {
            for(int i=0;i<APUCSC_12.allLightDuty.size();i++)
            {
                if(APUCSC_12.allLightDuty.get(i).getDay().equals(day) && APUCSC_12.allLightDuty.get(i).getBeginTime()==startTime && APUCSC_12.allLightDuty.get(i).getEndTime()==finishTime)
                {
                    jList2.setModel(dm2);
                    dm2.addElement(APUCSC_12.allLightDuty.get(i).getWorker().getUserId());
                }
            }
            for(int i=0;i<APUCSC_12.allTechs.size();i++)
            {
                jList3.setModel(dm);
                dm.addElement(APUCSC_12.allTechs.get(i).getUserId());
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Enter Customer Details first!!");
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_48.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_48.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_48.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_48.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_48().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
